[bot]
# whitelisted users id to run admin commands
admin_users_id = [
    7357
]
allowed_chats_id = []
report_chat_id = 7357
mastodon_api_key = ""

[[bot.rules]]
action = "block"
contains = [
    "bad word",
]

[routes]
# whitelisted ip addresses to access the routes
allowed_ip = [
    "91.108.56.0/22",
    "91.108.4.0/22",
    "91.108.8.0/22",
    "91.108.16.0/22",
    "91.108.12.0/22",
    "149.154.160.0/20",
    "91.105.192.0/23",
    "91.108.20.0/22",
    "185.76.151.0/24",
    "2001:b28:f23d::/48",
    "2001:b28:f23f::/48",
    "2001:67c:4e8::/48",
    "2001:b28:f23c::/48",
    "2a0a:f280::/32",
]
