name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: wiseass
    steps:
    - uses: actions/checkout@v3
    - name: prepare env
      run: touch .env
    - name: deploy
      run: make deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        KV_BINDING: ${{ secrets.KV_BINDING }}
        KV_ID: ${{ secrets.KV_ID }}
